### ISSUE TITLE
Race condition (”L.hs” bug in lambdabot)

### ISSUE THREAD

**Issue by haasn** [gwern/mueval#2]
In https://github.com/gwern/mueval/blob/master/Mueval/Interpreter.hs#L96, you just use /tmp/filename.hs as the temporary file location - rather than getting an actual new temporary file with a random name.

The ideal solution would be to use the system's API (System.IO.openTempFile) to create a temporary file.

**Comment by gwern** [comment]
I think [commit 0ce5c49e429fdd962c9b9afb8011315d095b2e23](https://github.com/gwern/mueval/commit/0ce5c49e429fdd962c9b9afb8011315d095b2e23) *should* fix this. However, the file/module copying stuff is complex and fragile so it could be broken. It seemed to work but I don't have a lot of confidence in it.
