### ISSUE TITLE
ExitFailure during haskell.org tutorial

### ISSUE THREAD

**Issue by coder543** [gwern/mueval#6]
I was running through the Haskell tutorial on the homepage just to see what it was like on the new website, and I ran into this issue. Re-running the command worked as I had expected it to work the first time, without error message, but I figured I should report the error anyways. Based on the "mueval" in the error message, this appears to be the project behind it, but maybe I should be reporting this somewhere else.

    λ (28,"chirs")
    mueval-core: Imports.hs: removeLink: does not exist (No such file or directory)
    ExitFailure 1

**Comment by gwern** [comment]
I'm not sure how that website works. Does mueval evaluate your functions without any issue if you run it locally? Because your example (which seems to just define a 2-tuple of an Int and a String) runs fine in my local mueval which I compiled yesterday from HEAD:

    $ mueval -e '(28,"chirs")'
    (28,"chirs")

**Comment by coder543** [comment]
Yes, and it ran fine the next time I executed the command, but there was some kind of transient error that occurred when I ran it the first time. The error did not happen subsequent times.

**Comment by chrisdone** [comment]
There's some kind of race condition that only happens under heavy load, but I haven't looked into it.

**Comment by chrisdone** [comment]
I think this was fixed in https://github.com/gwern/mueval/issues/2.
