### ISSUE TITLE
Allow function definitions

### ISSUE THREAD

**Issue by coder543** [gwern/mueval#7]
It doesn't seem possible to define functions in mueval, but maybe this is because mueval is stateless? Having looked at the README on here, it would appear that commands are executed in isolation, so there's no way for it to reference past executions -- like the definition of a function.

Is there any way this could be made possible?

**Comment by gwern** [comment]
That should be supported by the load-file functionality:

    -l FILE        --load-file=FILE         A local file for Mueval to load, providing definitions. Contents are trusted! Do not put anything dubious in it!

**Comment by chrisdone** [comment]
Is the impetus for this ticket the new haskell homepage (which is using tryhaskell)?

**Comment by coder543** [comment]
Yes, the haskell homepage. Does tryhaskell use mueval? Because the haskell homepage generated an error with the word mueval in it.

**Comment by chrisdone** [comment]
Yes, it does. `-l` would be the way to support something like this. It's just a little tricky to handle things like overwriting old bindings, especially pattern bindings.

**Comment by chrisdone** [comment]
Mueval also uses hint which only evaluates expressions, not statements. Closing as this seems answered from Mueval's perspective.
