### ISSUE TITLE
cannot build with ghc-7.10.1

### ISSUE THREAD

**Issue by jwaldmann** [gwern/mueval#8]
```
Preprocessing library mueval-0.9.1.1...
[1 of 5] Compiling Mueval.Resources ( Mueval/Resources.hs, dist/build/Mueval/Resources.o )
[2 of 5] Compiling Mueval.Context   ( Mueval/Context.hs, dist/build/Mueval/Context.o )
[3 of 5] Compiling Mueval.ArgsParse ( Mueval/ArgsParse.hs, dist/build/Mueval/ArgsParse.o )
[4 of 5] Compiling Mueval.Interpreter ( Mueval/Interpreter.hs, dist/build/Mueval/Interpreter.o )

Mueval/Interpreter.hs:163:7:
    Non type-variable argument
      in the constraint: Control.Monad.Writer.Class.MonadWriter Any f
    (Use FlexibleContexts to permit this)
```

**Comment by bergmark** [comment]
I've revised existing versions to disallow GHC 7.10 https://hackage.haskell.org/package/mueval/revisions/

This fix still needs to be released for 7.10 support.

**Comment by pharpend** [comment]
What's the status on this?

**Comment by gwern** [comment]
mueval HEAD has jwaldman's suggested fix merged in; I only have GHC version 7.6.3 installed from Debian so I can't confirm that it fixes the issue. Does the current version build and run for other people on GHC 7.10.x?

**Comment by pharpend** [comment]
It works-ish. It compiles just fine, but trying to run hello world gives me this:

```
[builds/mueval master] % mueval -e "print \"hello, world\""
mueval-core: GHC returned a result but said: [GhcError {errMsg = "Top level:\n    Module \8216Control.Monad.Error\8217 is deprecated:\n      Use Control.Monad.Except instead"}]
```

**Comment by gwern** [comment]
Looks like your GHC is not happy about the set of modules being imported/visible by default. Does the test suite work again if you try:

    diff --git a/Mueval/Context.hs b/Mueval/Context.hs
    index 548514c..2c2094c 100644
    --- a/Mueval/Context.hs
    +++ b/Mueval/Context.hs
    @@ -30,7 +30,7 @@ defaultModules = ["Prelude",
                       "Control.Arrow",
                       "Control.Monad",
                       "Control.Monad.Cont",
    -                  "Control.Monad.Error",
    +                  "Control.Monad.Except",
                       "Control.Monad.Fix",
                       "Control.Monad.Identity",
     #if !MIN_VERSION_base(4,7,0)

? It breaks on my GHC 7.6 but probably another CPP command can swap `Control.Monad.Error` for `Control.Monad.Except` for 7.10...

**Comment by bergmark** [comment]
@pharpend ping?

**Comment by pharpend** [comment]
On Fri, Jul 03, 2015 at 06:29:44AM -0700, Adam Bergmark wrote:
> @pharpend ping?

Sorry about the delay. My computer that has enough power to run GHC is
indisposed at the moment, so I can't test this for a couple of days
until I fix my computer.

Peter Harpending

**Comment by bergmark** [comment]
Ok i tested on GHC 7.10, the change you suggested is good @gwern.

There's (only) one more error:
```
show [] -E
    No instance for (Show t0) arising from a use of ‘show’
    The type variable ‘t0’ is ambiguous
    Note: there are several potential instances:
      instance Show a ⇒ Show (Const a b)
        -- Defined in ‘Control.Applicative’
      instance Show a ⇒ Show (ZipList a)
        -- Defined in ‘Control.Applicative’
      instance Show GeneralCategory -- Defined in ‘Data.Char’
      ...plus 116 others
    In the expression: show []
```

**Comment by pharpend** [comment]
And that's a simple case of needing a type annotation. Yay!

**Comment by bergmark** [comment]
it tests type defaulting so i assumed this was unwanted behavior, but i dunno

**Comment by gwern** [comment]
I think that specific test-case may've been broken for a while due to changes somewhere in GHC or `simple-reflect`, so probably it should just be ignored or removed from the test-suite - it doesn't seem like an important use-case that anyone really needs.

bergmark, can you test this change:

    diff --git a/Mueval/Context.hs b/Mueval/Context.hs
    index 548514c..98af5ec 100644
    --- a/Mueval/Context.hs
    +++ b/Mueval/Context.hs
    @@ -30,7 +30,11 @@ defaultModules = ["Prelude",
                       "Control.Arrow",
                       "Control.Monad",
                       "Control.Monad.Cont",
    +#if __GLASGOW_HASKELL__ >= 710
    +                  "Control.Monad.Except",
    +#else
                       "Control.Monad.Error",
    +#endif
                       "Control.Monad.Fix",
                       "Control.Monad.Identity",
     #if !MIN_VERSION_base(4,7,0)
    diff --git a/tests.sh b/tests.sh
    index 5a0a6cb..2ec49cc 100755
    --- a/tests.sh
    +++ b/tests.sh
    @@ -63,7 +63,6 @@ m "zipWith3 f [1,2..] [1,3..] [1,4..] :: [Expr]"
     m "sum [1..5] :: Expr"
     m "foldr f x [1..5]"
     ## Test defaulting of expressions
    -m 'show []' -E

If this works for everyone on GHC 7.10, then I can push it and upload a fresh mueval to Hackage, since the install problems should be (?) resolved now.

**Comment by bergmark** [comment]
:+1: works!

and yes i didn't have any install problems.

**Comment by gwern** [comment]
Pushed CPP change as a patch, bumped version, and uploaded to Hackage.

**Comment by bergmark** [comment]
Thanks Gwern!
